[project]
name = "ds-tutor"
version = "0.1.0"
description = "Interactive Data Science tutor helps to guide sklearn projects. This project is for people that are happy coding but would like reminders on the mathemtics behind certain data science processes."
readme = "README.md"
authors = [
    { name = "smdbz", email = "github.commodore391@passmail.net" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.2.0",
    "ipython>=9.10.0",
    "kaggle>=2.0.0",
    "pandas>=3.0.1",
    "plotly>=6.5.2",
    "scikit-learn>=1.8.0",
    "setuptools>=82.0.0",
    "yellowbrick>=1.5",
]

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "kagglehub>=1.0.0",
    "pytest>=9.0.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src/ds_tutor"]
